-- 기존 테이블 Drop (H2 데이터베이스 재시작 시 필요)
DROP TABLE IF EXISTS agent;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS users;

-- 회사 테이블
CREATE TABLE IF NOT EXISTS company (
    company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- 고객 테이블
CREATE TABLE IF NOT EXISTS client (
    client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ssn VARCHAR(20) NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    address VARCHAR(255),
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP NOT NULL,
    profile_image_url VARCHAR(255),
    email_verified BOOLEAN DEFAULT FALSE
);

-- 관리자 테이블
CREATE TABLE IF NOT EXISTS admin (
    admin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    address VARCHAR(255),
    role VARCHAR(20) NOT NULL DEFAULT 'ADMIN',
    created_at TIMESTAMP NOT NULL,
    email_verified BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (company_id) REFERENCES company(company_id)
);

-- 상담원 테이블
CREATE TABLE IF NOT EXISTS agent (
    agent_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    address VARCHAR(255),
    role VARCHAR(20) NOT NULL DEFAULT 'AGENT',
    state VARCHAR(20) NOT NULL DEFAULT 'INACTIVE',
    created_at TIMESTAMP NOT NULL,
    profile_image_url VARCHAR(255),
    email_verified BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (company_id) REFERENCES company(company_id)
);

-- 인덱스 생성
CREATE INDEX idx_admin_company_id ON admin(company_id);
CREATE INDEX idx_agent_company_id ON agent(company_id); 